language: php

dist: trusty
sudo: false

php:
  - '7.0'

env:
  - DB=mysql

before_script:
  - cp .env.travis .env
  - mysql -e 'create database certbot;'
  - composer self-update
  - composer install --no-interaction
  - ./artisan migrate
  - ./artisan key:generate
  - ./artisan jwt:secret

script:
  - vendor/bin/phpunit
